services:
  bifrost-postgres:
    image: postgres:18-alpine
    container_name: hlab-bifrost-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BIFROST_POSTGRES_DATABASE:?environment variable BIFROST_POSTGRES_DATABASE is not set.}
      POSTGRES_USER: ${BIFROST_POSTGRES_USER:?environment variable BIFROST_POSTGRES_USER is not set.}
      POSTGRES_PASSWORD: ${BIFROST_POSTGRES_PASSWORD:?environment variable BIFROST_POSTGRES_PASSWORD is not set.}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - bifrost-postgres-data:/var/lib/postgresql
    networks:
      - bifrost-net

  bifrost:
    image: maximhq/bifrost:v1.5.15
    container_name: hlab-bifrost
    restart: unless-stopped
    environment:
      BIFROST_POSTGRES_DATABASE: ${BIFROST_POSTGRES_DATABASE:?environment variable BIFROST_POSTGRES_DATABASE is not set.}
      BIFROST_POSTGRES_USER: ${BIFROST_POSTGRES_USER:?environment variable BIFROST_POSTGRES_USER is not set.}
      BIFROST_POSTGRES_PASSWORD: ${BIFROST_POSTGRES_PASSWORD:?environment variable BIFROST_POSTGRES_PASSWORD is not set.}
      BIFROST_ENCRYPTION_KEY: ${BIFROST_ENCRYPTION_KEY:?environment variable BIFROST_ENCRYPTION_KEY is not set.}
      BIFROST_ADMIN_USERNAME: ${BIFROST_ADMIN_USERNAME:?environment variable BIFROST_ADMIN_USERNAME is not set.}
      BIFROST_ADMIN_PASSWORD: ${BIFROST_ADMIN_PASSWORD:?environment variable BIFROST_ADMIN_PASSWORD is not set.}
      GEMINI_API_KEY_01: ${GEMINI_API_KEY_01:?environment variable GEMINI_API_KEY_01 is not set.}
      GEMINI_API_KEY_02: ${GEMINI_API_KEY_02:?environment variable GEMINI_API_KEY_02 is not set.}
      GEMINI_API_KEY_03: ${GEMINI_API_KEY_03:?environment variable GEMINI_API_KEY_03 is not set.}
      GEMINI_API_KEY_04: ${GEMINI_API_KEY_04:?environment variable GEMINI_API_KEY_04 is not set.}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:?environment variable OPENROUTER_API_KEY is not set.}
      GROQ_API_KEY: ${GROQ_API_KEY:?environment variable GROQ_API_KEY is not set.}
      CEREBRAS_API_KEY: ${CEREBRAS_API_KEY:?environment variable CEREBRAS_API_KEY is not set.}
    depends_on:
      bifrost-postgres:
        condition: service_healthy
    ports:
      - 5625:8080
    volumes:
      - ./config.json:/app/data/config.json:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:8080/health",
        ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    networks:
      - bifrost-net

volumes:
  bifrost-postgres-data:
    name: hlab-bifrost-postgres-data

networks:
  bifrost-net:
    name: hlab-bifrost-net
    driver: bridge
