# ----------------------------------------------------------------------
# HTTP to HTTPS REDIRECT
# ----------------------------------------------------------------------
server {
    listen 80;
    listen [::]:80;
    server_name listmonk.sammaji.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# ----------------------------------------------------------------------
# HTTPS CONFIGURATION
# ----------------------------------------------------------------------
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name listmonk.sammaji.com;

    ssl_certificate     /etc/letsencrypt/live/listmonk.sammaji.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/listmonk.sammaji.com/privkey.pem; # managed by Certbot

    # Media library uploads (campaign images) can exceed nginx's 1m default
    client_max_body_size 25m;

    location / {
        proxy_pass http://127.0.0.1:5655;
        include /etc/nginx/snippets/proxy-headers.conf;
    }
}
